# Generated by Django 4.2.7 on 2023-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
